development:
  host: 'http://192.168.99.100:9200'
  transport_options:
    request:
      timeout: 5

test:
  host: 'http://localhost:9200'
  transport_options:
    request:
      timeout: 5

production:
  host: 'http://localhost:9200'
  transport_options:
    request:
      timeout: 5
